# Generated by Django 5.1.3 on 2025-02-28 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'ordering': ['username'], 'verbose_name': 'MyUser ', 'verbose_name_plural': 'MyUsers'},
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='course',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='students',
        ),
        migrations.AddField(
            model_name='courses',
            name='assistant',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'assistant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courses',
            name='students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'student'}, related_name='student_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='courses',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('assistant', 'Assistant'), ('student', 'Student'), ('teacher', 'Teacher')], default='student', max_length=10),
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='accounts.courses')),
            ],
        ),
        migrations.AddField(
            model_name='lessons',
            name='module',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='accounts.modules'),
            preserve_default=False,
        ),
    ]
