# Generated by Django 5.1.6 on 2025-03-05 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_myuser_options_remove_lessons_course_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modules',
            options={'ordering': ['name'], 'verbose_name': 'Module ', 'verbose_name_plural': 'Modules'},
        ),
    ]
