# Generated by Django 5.1.6 on 2025-03-05 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_modules_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('admin', 'Admin'), ('assistant', 'Assistant'), ('student', 'Student'), ('teacher', 'Teacher')], max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='courses',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.ForeignKey(default='student', on_delete=django.db.models.deletion.CASCADE, to='accounts.customrole'),
        ),
    ]
