# Generated by Django 5.1.6 on 2025-03-05 12:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_courses_assistant_alter_courses_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='student_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
