# Generated by Django 5.1.6 on 2025-03-09 01:31

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_courses_slug_lessons_slug_modules_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/'),
        ),
        migrations.AlterField(
            model_name='lessonfile',
            name='file',
            field=models.FileField(upload_to='lessons/', validators=[accounts.validators.validate_file_extension]),
        ),
    ]
