# Generated by Django 5.1.6 on 2025-03-09 01:33

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_courses_image_alter_lessonfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='module_images/', validators=[accounts.validators.validate_file_extension]),
        ),
    ]
