# Generated by Django 5.1.7 on 2025-03-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_myuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myuser',
            name='courses',
            field=models.ManyToManyField(related_name='courses', to='accounts.courses'),
        ),
    ]
