# Generated by Django 5.1.7 on 2025-03-10 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_courses_price_myuser_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='students',
        ),
    ]
