# Generated by Django 5.1.7 on 2025-03-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_courses_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='courses', to='accounts.courses'),
        ),
    ]
