# Generated by Django 5.1.7 on 2025-03-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_myuser_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='muted',
            field=models.BooleanField(default=False),
        ),
    ]
