# Generated by Django 5.1.7 on 2025-03-25 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='image',
        ),
        migrations.AddField(
            model_name='notification',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='notification_banner/'),
        ),
    ]
